name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login-dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-and-push-v13
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seeeverything/pre-commit-terraform:0.13
          build-args: TERRAFORM_VERSION=0.13.7
      - name: build-and-push-v15
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seeeverything/pre-commit-terraform:0.15
          build-args: TERRAFORM_VERSION=0.15.4
